version: "3.0"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - postgres
      - redis
      - mailhog
    environment:
      NOTIFICATIONS_ENV: ${NOTIFICATIONS_ENV}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      DB_HOST: ${DB_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      MAILHOG_HOST: ${MAILHOG_HOST}
      UOW: ${UOW}
      SECRET_KEY: ${SECRET_KEY}
      DB_SYNC_URL: ${DB_SYNC_URL}
      API_PORT: ${API_PORT}
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    healthcheck:
      test: redis-cli ping
      interval: 3s
      timeout: 5s
      retries: 5

  redisinsight:
    image: "redislabs/redisinsight:latest"
    ports:
      - "127.0.0.1:8001:8001"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
