"""new changes to the model

Revision ID: f91c4e78f21c
Revises: 
Create Date: 2023-06-25 14:34:11.030608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f91c4e78f21c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        "orders", sa.Column("is_deleted", sa.Integer(), nullable=True)
    )
    op.execute("UPDATE orders SET is_deleted = 0 WHERE is_deleted IS NULL")
    op.alter_column("orders", "is_deleted", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "is_deleted")
    # ### end Alembic commands ###
